In [2]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np


In [3]:
(X_train, y_train), (X_test, y_test) = datasets.mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [5]:
X_train.shape
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
cnn = models.Sequential([
    layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])
cnn.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
cnn.fit(X_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 39s 20ms/step - loss: 0.3416 - accuracy: 0.9331
Epoch 2/5
1875/1875 [==============================] - 38s 20ms/step - loss: 0.0665 - accuracy: 0.9800
Epoch 3/5
1875/1875 [==============================] - 37s 20ms/step - loss: 0.0530 - accuracy: 0.9834
Epoch 4/5
1875/1875 [==============================] - 39s 21ms/step - loss: 0.0441 - accuracy: 0.9862
Epoch 5/5
1875/1875 [==============================] - 40s 21ms/step - loss: 0.0357 - accuracy: 0.9892


In [9]:
cnn.evaluate(X_test,y_test)

313/313 [==============================] - 3s 9ms/step - loss: 0.0411 - accuracy: 0.9868


[0.04114663600921631, 0.9868000149726868]

In [12]:
yp = cnn.predict(X_test)
yp = np.argmax(yp,axis=1)
yp

313/313 [==============================] - 2s 7ms/step


array([7, 2, 1, ..., 4, 5, 6])

In [13]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [14]:
from sklearn.metrics import classification_report
print("Classification Report:\n", classification_report(y_test, yp))

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       1.00      0.99      0.99      1135
           2       0.99      0.98      0.98      1032
           3       0.98      0.99      0.98      1010
           4       0.99      0.99      0.99       982
           5       0.98      0.98      0.98       892
           6       0.99      0.99      0.99       958
           7       0.98      1.00      0.99      1028
           8       0.99      0.98      0.99       974
           9       0.99      0.98      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

